version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    image: golemBackend
  redis:
    image: redis
volumes:
  logvolume01: {}